### ISSUE TITLE
Something wrong in catkin_make step

### ISSUE THREAD

**Issue by Denghaoyuan123** [TempleRAIL/drl_vo_nav#18]
Thanks for giving such a excellent project!

I am new in Robot and face some error that I cant do anything to deal with, during run your project, exactly in the step of "catkin_make"
following is my log file ,I hope that you can give me some reply to fix it!

[build.log](https://github.com/TempleRAIL/drl_vo_nav/files/14123307/build.log)

**Comment by zzuxzt** [comment]
It seems to be a problem with your system configuration. Please make sure your system has a C++ compiler installed. Normally it should look like the log below:
```
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
```
Try the following commands:
```
sudo apt install build-essential
cd /home/dhy/Temple11111111111111111/catkin_ws/
rm -rf build/ devel/
catkin_make
```
If you are new to ROS and cannot let it work, I recommend using my pre-built Singularity ["drl_vo_container.sif"](https://doi.org/10.5281/zenodo.7679658) and following installation 2) operations rather than configuring the environment yourself.
